packages:
  - packages/*
  - apps/*
  - tooling/*
  - configs
catalog:
  "@types/node": 22.13.0
  "@eslint/js": ^9.4.0
  "eslint": ^8.57.0
  "eslint-config-prettier": ^9.1.0
  "eslint-plugin-import": ^2.29.1
  "eslint-plugin-prettier": ^5.1.3
  "eslint-plugin-unicorn": ^53.0.0
  "eslint-plugin-unused-imports": ^3.1.0
  "prettier": ^3.2.5
  "typescript-eslint": ^8.28.0
  "typescript": ^5.4.5
  "vitest": ^3.0.9
  "tsup": ^8.4.0
  "@arethetypeswrong/cli": ^0.17.4
onlyBuiltDependencies:
  - esbuild
